//! Generated and Identity Columns
//!
//! Provides:
//! - GENERATED ALWAYS AS IDENTITY / GENERATED BY DEFAULT AS IDENTITY
//! - GENERATED ALWAYS AS (expression) STORED / VIRTUAL

use parking_lot::RwLock;
use serde::{Deserialize, Serialize};
use std::collections::HashMap;
use std::sync::Arc;

/// Generated column error types
#[derive(Debug, Clone)]
pub enum GeneratedColumnError {
    /// Column not found
    ColumnNotFound(String),
    /// Cannot insert into generated column
    CannotInsert(String),
    /// Cannot update generated column
    CannotUpdate(String),
    /// Expression evaluation failed
    ExpressionError(String),
    /// Circular dependency
    CircularDependency(String),
    /// Invalid definition
    InvalidDefinition(String),
    /// Sequence error
    SequenceError(String),
}

impl std::fmt::Display for GeneratedColumnError {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            Self::ColumnNotFound(s) => write!(f, "column not found: {}", s),
            Self::CannotInsert(s) => write!(f, "cannot insert into generated column: {}", s),
            Self::CannotUpdate(s) => write!(f, "cannot update generated column: {}", s),
            Self::ExpressionError(s) => write!(f, "expression error: {}", s),
            Self::CircularDependency(s) => write!(f, "circular dependency: {}", s),
            Self::InvalidDefinition(s) => write!(f, "invalid definition: {}", s),
            Self::SequenceError(s) => write!(f, "sequence error: {}", s),
        }
    }
}

impl std::error::Error for GeneratedColumnError {}

/// Identity column definition
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct IdentityColumn {
    /// Column name
    pub column_name: String,
    /// Identity type (ALWAYS or BY DEFAULT)
    pub identity_type: IdentityType,
    /// Sequence name (auto-generated)
    pub sequence_name: String,
    /// Sequence options
    pub sequence_options: IdentitySequenceOptions,
}

/// Identity generation type
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
pub enum IdentityType {
    /// GENERATED ALWAYS AS IDENTITY - error if value provided
    Always,
    /// GENERATED BY DEFAULT AS IDENTITY - use provided value or generate
    ByDefault,
}

/// Sequence options for identity column
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct IdentitySequenceOptions {
    pub start: Option<i64>,
    pub increment: Option<i64>,
    pub min_value: Option<i64>,
    pub max_value: Option<i64>,
    pub cycle: Option<bool>,
    pub cache: Option<u32>,
}

/// Generated column definition
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct GeneratedColumn {
    /// Column name
    pub column_name: String,
    /// Generation expression
    pub expression: String,
    /// Storage type
    pub storage_type: GeneratedStorageType,
    /// Columns this depends on
    pub depends_on: Vec<String>,
    /// Result data type
    pub data_type: String,
}

/// Generated column storage type
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
pub enum GeneratedStorageType {
    /// Computed and stored on write
    Stored,
    /// Computed on read (virtual)
    Virtual,
}

impl Default for GeneratedStorageType {
    fn default() -> Self {
        Self::Stored
    }
}

/// Column value for generation
#[derive(Debug, Clone, Serialize, Deserialize)]
pub enum ColumnValue {
    Null,
    Boolean(bool),
    Int64(i64),
    Float64(f64),
    String(String),
    Bytes(Vec<u8>),
    Timestamp(i64),
    Date(i32),
    Decimal(String),
    Array(Vec<ColumnValue>),
    Default, // Use default/generated value
}

impl ColumnValue {
    pub fn is_default(&self) -> bool {
        matches!(self, Self::Default)
    }

    pub fn as_i64(&self) -> Option<i64> {
        match self {
            Self::Int64(v) => Some(*v),
            Self::Float64(v) => Some(*v as i64),
            _ => None,
        }
    }

    pub fn as_f64(&self) -> Option<f64> {
        match self {
            Self::Float64(v) => Some(*v),
            Self::Int64(v) => Some(*v as f64),
            _ => None,
        }
    }

    pub fn as_string(&self) -> Option<&str> {
        match self {
            Self::String(s) => Some(s),
            _ => None,
        }
    }

    pub fn as_bool(&self) -> Option<bool> {
        match self {
            Self::Boolean(b) => Some(*b),
            _ => None,
        }
    }
}

/// Row data for generated column computation
pub type RowData = HashMap<String, ColumnValue>;

/// Expression evaluator trait
pub trait ExpressionEvaluator: Send + Sync {
    /// Evaluate expression with row context
    fn evaluate(
        &self,
        expression: &str,
        row: &RowData,
    ) -> Result<ColumnValue, GeneratedColumnError>;
}

/// Simple expression evaluator (for basic operations)
pub struct SimpleExpressionEvaluator;

impl ExpressionEvaluator for SimpleExpressionEvaluator {
    fn evaluate(
        &self,
        expression: &str,
        row: &RowData,
    ) -> Result<ColumnValue, GeneratedColumnError> {
        let expr = expression.trim();

        // Handle simple column references
        if let Some(value) = row.get(expr) {
            return Ok(value.clone());
        }

        // Handle simple arithmetic: col1 + col2, col1 * 2, etc.
        if let Some(result) = self.evaluate_arithmetic(expr, row) {
            return result;
        }

        // Handle CONCAT
        if expr.to_uppercase().starts_with("CONCAT(") {
            return self.evaluate_concat(expr, row);
        }

        // Handle UPPER/LOWER
        if expr.to_uppercase().starts_with("UPPER(") {
            return self.evaluate_upper(expr, row);
        }
        if expr.to_uppercase().starts_with("LOWER(") {
            return self.evaluate_lower(expr, row);
        }

        // Handle COALESCE
        if expr.to_uppercase().starts_with("COALESCE(") {
            return self.evaluate_coalesce(expr, row);
        }

        // Handle literals
        if let Some(result) = self.parse_literal(expr) {
            return Ok(result);
        }

        Err(GeneratedColumnError::ExpressionError(format!(
            "unsupported expression: {}",
            expression
        )))
    }
}

impl SimpleExpressionEvaluator {
    fn evaluate_arithmetic(
        &self,
        expr: &str,
        row: &RowData,
    ) -> Option<Result<ColumnValue, GeneratedColumnError>> {
        // Check for operators - try each one
        let operators: &[(&str, fn(f64, f64) -> f64)] = &[
            (" + ", |a, b| a + b),
            (" - ", |a, b| a - b),
            (" * ", |a, b| a * b),
            (" / ", |a, b| a / b),
        ];

        for (op_str, op_fn) in operators.iter() {
            if let Some(pos) = expr.find(op_str) {
                let left = expr[..pos].trim();
                let right = expr[pos + op_str.len()..].trim();

                let left_val = self.get_numeric(left, row)?;
                let right_val = self.get_numeric(right, row)?;

                let result = op_fn(left_val, right_val);

                // Return as i64 if no decimal part
                if result.fract() == 0.0 {
                    return Some(Ok(ColumnValue::Int64(result as i64)));
                } else {
                    return Some(Ok(ColumnValue::Float64(result)));
                }
            }
        }

        None
    }

    fn get_numeric(&self, expr: &str, row: &RowData) -> Option<f64> {
        // Try as column reference
        if let Some(value) = row.get(expr) {
            return value.as_f64();
        }

        // Try as literal
        expr.parse::<f64>().ok()
    }

    fn evaluate_concat(
        &self,
        expr: &str,
        row: &RowData,
    ) -> Result<ColumnValue, GeneratedColumnError> {
        // CONCAT(col1, col2, ...)
        let inner = expr
            .strip_prefix("CONCAT(")
            .or_else(|| expr.strip_prefix("concat("))
            .and_then(|s| s.strip_suffix(')'))
            .ok_or_else(|| GeneratedColumnError::ExpressionError("invalid CONCAT".into()))?;

        let mut result = String::new();
        for part in inner.split(',') {
            let part = part.trim();
            if let Some(value) = row.get(part) {
                match value {
                    ColumnValue::String(s) => result.push_str(s),
                    ColumnValue::Int64(n) => result.push_str(&n.to_string()),
                    ColumnValue::Float64(f) => result.push_str(&f.to_string()),
                    ColumnValue::Boolean(b) => result.push_str(&b.to_string()),
                    ColumnValue::Null => {}
                    _ => {}
                }
            } else if let Some(literal) = self.parse_string_literal(part) {
                result.push_str(&literal);
            }
        }

        Ok(ColumnValue::String(result))
    }

    fn evaluate_upper(
        &self,
        expr: &str,
        row: &RowData,
    ) -> Result<ColumnValue, GeneratedColumnError> {
        let inner = expr
            .strip_prefix("UPPER(")
            .or_else(|| expr.strip_prefix("upper("))
            .and_then(|s| s.strip_suffix(')'))
            .ok_or_else(|| GeneratedColumnError::ExpressionError("invalid UPPER".into()))?
            .trim();

        let value = row
            .get(inner)
            .ok_or_else(|| GeneratedColumnError::ColumnNotFound(inner.to_string()))?;

        match value {
            ColumnValue::String(s) => Ok(ColumnValue::String(s.to_uppercase())),
            ColumnValue::Null => Ok(ColumnValue::Null),
            _ => Err(GeneratedColumnError::ExpressionError(
                "UPPER requires string".into(),
            )),
        }
    }

    fn evaluate_lower(
        &self,
        expr: &str,
        row: &RowData,
    ) -> Result<ColumnValue, GeneratedColumnError> {
        let inner = expr
            .strip_prefix("LOWER(")
            .or_else(|| expr.strip_prefix("lower("))
            .and_then(|s| s.strip_suffix(')'))
            .ok_or_else(|| GeneratedColumnError::ExpressionError("invalid LOWER".into()))?
            .trim();

        let value = row
            .get(inner)
            .ok_or_else(|| GeneratedColumnError::ColumnNotFound(inner.to_string()))?;

        match value {
            ColumnValue::String(s) => Ok(ColumnValue::String(s.to_lowercase())),
            ColumnValue::Null => Ok(ColumnValue::Null),
            _ => Err(GeneratedColumnError::ExpressionError(
                "LOWER requires string".into(),
            )),
        }
    }

    fn evaluate_coalesce(
        &self,
        expr: &str,
        row: &RowData,
    ) -> Result<ColumnValue, GeneratedColumnError> {
        let inner = expr
            .strip_prefix("COALESCE(")
            .or_else(|| expr.strip_prefix("coalesce("))
            .and_then(|s| s.strip_suffix(')'))
            .ok_or_else(|| GeneratedColumnError::ExpressionError("invalid COALESCE".into()))?;

        for part in inner.split(',') {
            let part = part.trim();
            if let Some(value) = row.get(part) {
                if !matches!(value, ColumnValue::Null) {
                    return Ok(value.clone());
                }
            } else if let Some(literal) = self.parse_literal(part) {
                if !matches!(literal, ColumnValue::Null) {
                    return Ok(literal);
                }
            }
        }

        Ok(ColumnValue::Null)
    }

    fn parse_literal(&self, expr: &str) -> Option<ColumnValue> {
        let expr = expr.trim();

        // NULL
        if expr.eq_ignore_ascii_case("NULL") {
            return Some(ColumnValue::Null);
        }

        // Boolean
        if expr.eq_ignore_ascii_case("TRUE") {
            return Some(ColumnValue::Boolean(true));
        }
        if expr.eq_ignore_ascii_case("FALSE") {
            return Some(ColumnValue::Boolean(false));
        }

        // String literal
        if let Some(s) = self.parse_string_literal(expr) {
            return Some(ColumnValue::String(s));
        }

        // Number
        if let Ok(n) = expr.parse::<i64>() {
            return Some(ColumnValue::Int64(n));
        }
        if let Ok(f) = expr.parse::<f64>() {
            return Some(ColumnValue::Float64(f));
        }

        None
    }

    fn parse_string_literal(&self, expr: &str) -> Option<String> {
        let expr = expr.trim();
        if (expr.starts_with('\'') && expr.ends_with('\''))
            || (expr.starts_with('"') && expr.ends_with('"'))
        {
            Some(expr[1..expr.len() - 1].to_string())
        } else {
            None
        }
    }
}

/// Table generated columns manager
pub struct GeneratedColumnsManager {
    /// Identity columns per table (schema.table -> columns)
    identity_columns: RwLock<HashMap<String, Vec<IdentityColumn>>>,
    /// Generated columns per table
    generated_columns: RwLock<HashMap<String, Vec<GeneratedColumn>>>,
    /// Expression evaluator
    evaluator: Arc<dyn ExpressionEvaluator>,
}

impl GeneratedColumnsManager {
    pub fn new() -> Self {
        Self {
            identity_columns: RwLock::new(HashMap::new()),
            generated_columns: RwLock::new(HashMap::new()),
            evaluator: Arc::new(SimpleExpressionEvaluator),
        }
    }

    pub fn with_evaluator(evaluator: Arc<dyn ExpressionEvaluator>) -> Self {
        Self {
            identity_columns: RwLock::new(HashMap::new()),
            generated_columns: RwLock::new(HashMap::new()),
            evaluator,
        }
    }

    /// Add identity column
    pub fn add_identity_column(
        &self,
        schema: &str,
        table: &str,
        column: IdentityColumn,
    ) -> Result<(), GeneratedColumnError> {
        let table_key = format!("{}.{}", schema, table);

        let mut identity_cols = self.identity_columns.write();
        let cols = identity_cols.entry(table_key).or_insert_with(Vec::new);

        // Check for duplicate
        if cols.iter().any(|c| c.column_name == column.column_name) {
            return Err(GeneratedColumnError::InvalidDefinition(format!(
                "identity column {} already exists",
                column.column_name
            )));
        }

        cols.push(column);
        Ok(())
    }

    /// Add generated column
    pub fn add_generated_column(
        &self,
        schema: &str,
        table: &str,
        column: GeneratedColumn,
    ) -> Result<(), GeneratedColumnError> {
        let table_key = format!("{}.{}", schema, table);

        // Check for circular dependencies
        self.check_circular_dependency(schema, table, &column)?;

        let mut gen_cols = self.generated_columns.write();
        let cols = gen_cols.entry(table_key).or_insert_with(Vec::new);

        // Check for duplicate
        if cols.iter().any(|c| c.column_name == column.column_name) {
            return Err(GeneratedColumnError::InvalidDefinition(format!(
                "generated column {} already exists",
                column.column_name
            )));
        }

        cols.push(column);
        Ok(())
    }

    fn check_circular_dependency(
        &self,
        _schema: &str,
        _table: &str,
        column: &GeneratedColumn,
    ) -> Result<(), GeneratedColumnError> {
        // Check that the column doesn't depend on itself
        if column.depends_on.contains(&column.column_name) {
            return Err(GeneratedColumnError::CircularDependency(format!(
                "column {} depends on itself",
                column.column_name
            )));
        }

        // More complex cycle detection would check transitive dependencies
        Ok(())
    }

    /// Remove identity column
    pub fn remove_identity_column(
        &self,
        schema: &str,
        table: &str,
        column_name: &str,
    ) -> Result<(), GeneratedColumnError> {
        let table_key = format!("{}.{}", schema, table);

        let mut identity_cols = self.identity_columns.write();
        if let Some(cols) = identity_cols.get_mut(&table_key) {
            let len_before = cols.len();
            cols.retain(|c| c.column_name != column_name);
            if cols.len() == len_before {
                return Err(GeneratedColumnError::ColumnNotFound(
                    column_name.to_string(),
                ));
            }
        } else {
            return Err(GeneratedColumnError::ColumnNotFound(
                column_name.to_string(),
            ));
        }

        Ok(())
    }

    /// Remove generated column
    pub fn remove_generated_column(
        &self,
        schema: &str,
        table: &str,
        column_name: &str,
    ) -> Result<(), GeneratedColumnError> {
        let table_key = format!("{}.{}", schema, table);

        let mut gen_cols = self.generated_columns.write();
        if let Some(cols) = gen_cols.get_mut(&table_key) {
            let len_before = cols.len();
            cols.retain(|c| c.column_name != column_name);
            if cols.len() == len_before {
                return Err(GeneratedColumnError::ColumnNotFound(
                    column_name.to_string(),
                ));
            }
        } else {
            return Err(GeneratedColumnError::ColumnNotFound(
                column_name.to_string(),
            ));
        }

        Ok(())
    }

    /// Get identity columns for a table
    pub fn get_identity_columns(&self, schema: &str, table: &str) -> Vec<IdentityColumn> {
        let table_key = format!("{}.{}", schema, table);
        self.identity_columns
            .read()
            .get(&table_key)
            .cloned()
            .unwrap_or_default()
    }

    /// Get generated columns for a table
    pub fn get_generated_columns(&self, schema: &str, table: &str) -> Vec<GeneratedColumn> {
        let table_key = format!("{}.{}", schema, table);
        self.generated_columns
            .read()
            .get(&table_key)
            .cloned()
            .unwrap_or_default()
    }

    /// Check if column is identity
    pub fn is_identity_column(&self, schema: &str, table: &str, column: &str) -> bool {
        let table_key = format!("{}.{}", schema, table);
        self.identity_columns
            .read()
            .get(&table_key)
            .map_or(false, |cols| cols.iter().any(|c| c.column_name == column))
    }

    /// Check if column is generated
    pub fn is_generated_column(&self, schema: &str, table: &str, column: &str) -> bool {
        let table_key = format!("{}.{}", schema, table);
        self.generated_columns
            .read()
            .get(&table_key)
            .map_or(false, |cols| cols.iter().any(|c| c.column_name == column))
    }

    /// Get identity column definition
    pub fn get_identity_column(
        &self,
        schema: &str,
        table: &str,
        column: &str,
    ) -> Option<IdentityColumn> {
        let table_key = format!("{}.{}", schema, table);
        self.identity_columns
            .read()
            .get(&table_key)
            .and_then(|cols| cols.iter().find(|c| c.column_name == column).cloned())
    }

    /// Validate INSERT values for identity columns
    pub fn validate_identity_insert(
        &self,
        schema: &str,
        table: &str,
        columns: &[String],
        values: &[ColumnValue],
    ) -> Result<(), GeneratedColumnError> {
        let identity_cols = self.get_identity_columns(schema, table);

        for id_col in &identity_cols {
            if let Some(pos) = columns.iter().position(|c| c == &id_col.column_name) {
                // Value provided for identity column
                match id_col.identity_type {
                    IdentityType::Always => {
                        // Check if value is DEFAULT
                        if !values[pos].is_default() {
                            return Err(GeneratedColumnError::CannotInsert(format!(
                                "cannot insert into GENERATED ALWAYS column {}",
                                id_col.column_name
                            )));
                        }
                    }
                    IdentityType::ByDefault => {
                        // Allowed to provide value
                    }
                }
            }
        }

        Ok(())
    }

    /// Validate UPDATE values for generated columns
    pub fn validate_generated_update(
        &self,
        schema: &str,
        table: &str,
        columns: &[String],
    ) -> Result<(), GeneratedColumnError> {
        let gen_cols = self.get_generated_columns(schema, table);
        let identity_cols = self.get_identity_columns(schema, table);

        for col in columns {
            // Check generated columns
            if gen_cols.iter().any(|c| &c.column_name == col) {
                return Err(GeneratedColumnError::CannotUpdate(format!(
                    "cannot update generated column {}",
                    col
                )));
            }

            // Check identity columns
            for id_col in &identity_cols {
                if &id_col.column_name == col {
                    if id_col.identity_type == IdentityType::Always {
                        return Err(GeneratedColumnError::CannotUpdate(format!(
                            "cannot update GENERATED ALWAYS identity column {}",
                            col
                        )));
                    }
                }
            }
        }

        Ok(())
    }

    /// Compute generated column values for a row
    pub fn compute_generated_values(
        &self,
        schema: &str,
        table: &str,
        row: &mut RowData,
    ) -> Result<(), GeneratedColumnError> {
        let gen_cols = self.get_generated_columns(schema, table);

        // Sort by dependencies (simple topological sort)
        let sorted = self.topological_sort(&gen_cols)?;

        for col in sorted {
            let value = self.evaluator.evaluate(&col.expression, row)?;
            row.insert(col.column_name.clone(), value);
        }

        Ok(())
    }

    fn topological_sort(
        &self,
        columns: &[GeneratedColumn],
    ) -> Result<Vec<GeneratedColumn>, GeneratedColumnError> {
        // Simple topological sort implementation
        let mut sorted = Vec::new();
        let mut remaining: Vec<_> = columns.to_vec();
        let sorted_names: std::collections::HashSet<String> = std::collections::HashSet::new();

        while !remaining.is_empty() {
            let mut progress = false;

            // Collect columns whose dependencies are satisfied
            let mut to_add = Vec::new();
            let remaining_names: std::collections::HashSet<_> =
                remaining.iter().map(|c| c.column_name.clone()).collect();
            let sorted_names: std::collections::HashSet<_> = sorted
                .iter()
                .map(|c: &GeneratedColumn| c.column_name.clone())
                .collect();

            for (i, col) in remaining.iter().enumerate() {
                let deps_satisfied = col.depends_on.iter().all(|dep| {
                    // Either it's a base column (not in remaining) or already sorted
                    !remaining_names.contains(dep) || sorted_names.contains(dep)
                });

                if deps_satisfied {
                    to_add.push(i);
                }
            }

            // Add satisfied columns in reverse order to preserve indices
            for i in to_add.into_iter().rev() {
                sorted.push(remaining.remove(i));
                progress = true;
            }

            if !progress && !remaining.is_empty() {
                return Err(GeneratedColumnError::CircularDependency(
                    "circular dependency in generated columns".into(),
                ));
            }
        }

        Ok(sorted)
    }

    /// Get stored generated columns that need recomputation
    pub fn get_stored_columns(&self, schema: &str, table: &str) -> Vec<GeneratedColumn> {
        self.get_generated_columns(schema, table)
            .into_iter()
            .filter(|c| c.storage_type == GeneratedStorageType::Stored)
            .collect()
    }

    /// Get virtual generated columns
    pub fn get_virtual_columns(&self, schema: &str, table: &str) -> Vec<GeneratedColumn> {
        self.get_generated_columns(schema, table)
            .into_iter()
            .filter(|c| c.storage_type == GeneratedStorageType::Virtual)
            .collect()
    }
}

impl Default for GeneratedColumnsManager {
    fn default() -> Self {
        Self::new()
    }
}

/// Builder for creating identity column definitions
pub struct IdentityColumnBuilder {
    column_name: String,
    identity_type: IdentityType,
    options: IdentitySequenceOptions,
}

impl IdentityColumnBuilder {
    pub fn new(column_name: &str) -> Self {
        Self {
            column_name: column_name.to_string(),
            identity_type: IdentityType::Always,
            options: IdentitySequenceOptions::default(),
        }
    }

    pub fn always(mut self) -> Self {
        self.identity_type = IdentityType::Always;
        self
    }

    pub fn by_default(mut self) -> Self {
        self.identity_type = IdentityType::ByDefault;
        self
    }

    pub fn start_with(mut self, value: i64) -> Self {
        self.options.start = Some(value);
        self
    }

    pub fn increment_by(mut self, value: i64) -> Self {
        self.options.increment = Some(value);
        self
    }

    pub fn min_value(mut self, value: i64) -> Self {
        self.options.min_value = Some(value);
        self
    }

    pub fn max_value(mut self, value: i64) -> Self {
        self.options.max_value = Some(value);
        self
    }

    pub fn cycle(mut self) -> Self {
        self.options.cycle = Some(true);
        self
    }

    pub fn no_cycle(mut self) -> Self {
        self.options.cycle = Some(false);
        self
    }

    pub fn cache(mut self, size: u32) -> Self {
        self.options.cache = Some(size);
        self
    }

    pub fn build(self, schema: &str, table: &str) -> IdentityColumn {
        IdentityColumn {
            column_name: self.column_name.clone(),
            identity_type: self.identity_type,
            sequence_name: format!("{}_{}_seq", table, self.column_name),
            sequence_options: self.options,
        }
    }
}

/// Builder for creating generated column definitions
pub struct GeneratedColumnBuilder {
    column_name: String,
    expression: String,
    storage_type: GeneratedStorageType,
    depends_on: Vec<String>,
    data_type: String,
}

impl GeneratedColumnBuilder {
    pub fn new(column_name: &str, expression: &str) -> Self {
        Self {
            column_name: column_name.to_string(),
            expression: expression.to_string(),
            storage_type: GeneratedStorageType::Stored,
            depends_on: Vec::new(),
            data_type: "unknown".to_string(),
        }
    }

    pub fn stored(mut self) -> Self {
        self.storage_type = GeneratedStorageType::Stored;
        self
    }

    pub fn virtual_col(mut self) -> Self {
        self.storage_type = GeneratedStorageType::Virtual;
        self
    }

    pub fn depends_on(mut self, columns: Vec<&str>) -> Self {
        self.depends_on = columns.into_iter().map(String::from).collect();
        self
    }

    pub fn data_type(mut self, dtype: &str) -> Self {
        self.data_type = dtype.to_string();
        self
    }

    pub fn build(self) -> GeneratedColumn {
        GeneratedColumn {
            column_name: self.column_name,
            expression: self.expression,
            storage_type: self.storage_type,
            depends_on: self.depends_on,
            data_type: self.data_type,
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_identity_column() {
        let manager = GeneratedColumnsManager::new();

        let identity = IdentityColumnBuilder::new("id")
            .always()
            .start_with(1)
            .increment_by(1)
            .build("public", "users");

        manager
            .add_identity_column("public", "users", identity)
            .unwrap();

        assert!(manager.is_identity_column("public", "users", "id"));
        assert!(!manager.is_identity_column("public", "users", "name"));
    }

    #[test]
    fn test_generated_column() {
        let manager = GeneratedColumnsManager::new();

        let gen_col =
            GeneratedColumnBuilder::new("full_name", "CONCAT(first_name, ' ', last_name)")
                .stored()
                .depends_on(vec!["first_name", "last_name"])
                .data_type("VARCHAR")
                .build();

        manager
            .add_generated_column("public", "users", gen_col)
            .unwrap();

        assert!(manager.is_generated_column("public", "users", "full_name"));
    }

    #[test]
    fn test_validate_identity_insert() {
        let manager = GeneratedColumnsManager::new();

        let identity = IdentityColumnBuilder::new("id")
            .always()
            .build("public", "users");

        manager
            .add_identity_column("public", "users", identity)
            .unwrap();

        // Inserting into GENERATED ALWAYS should fail
        let result = manager.validate_identity_insert(
            "public",
            "users",
            &["id".to_string(), "name".to_string()],
            &[
                ColumnValue::Int64(1),
                ColumnValue::String("test".to_string()),
            ],
        );
        assert!(result.is_err());

        // Using DEFAULT should succeed
        let result = manager.validate_identity_insert(
            "public",
            "users",
            &["id".to_string(), "name".to_string()],
            &[
                ColumnValue::Default,
                ColumnValue::String("test".to_string()),
            ],
        );
        assert!(result.is_ok());
    }

    #[test]
    fn test_compute_generated_values() {
        let manager = GeneratedColumnsManager::new();

        // Add generated column: total = price * quantity
        let gen_col = GeneratedColumnBuilder::new("total", "price * quantity")
            .stored()
            .depends_on(vec!["price", "quantity"])
            .build();

        manager
            .add_generated_column("public", "orders", gen_col)
            .unwrap();

        // Create row data
        let mut row = RowData::new();
        row.insert("price".to_string(), ColumnValue::Float64(10.0));
        row.insert("quantity".to_string(), ColumnValue::Int64(5));

        // Compute generated values
        manager
            .compute_generated_values("public", "orders", &mut row)
            .unwrap();

        // Check result
        assert!(row.contains_key("total"));
        if let Some(ColumnValue::Int64(total)) = row.get("total") {
            assert_eq!(*total, 50);
        } else {
            panic!("expected Int64 total");
        }
    }

    #[test]
    fn test_expression_evaluator() {
        let evaluator = SimpleExpressionEvaluator;

        let mut row = RowData::new();
        row.insert(
            "first_name".to_string(),
            ColumnValue::String("John".to_string()),
        );
        row.insert(
            "last_name".to_string(),
            ColumnValue::String("Doe".to_string()),
        );

        // Test CONCAT
        let result = evaluator
            .evaluate("CONCAT(first_name, ' ', last_name)", &row)
            .unwrap();
        assert!(matches!(result, ColumnValue::String(s) if s == "John Doe"));

        // Test UPPER
        let result = evaluator.evaluate("UPPER(first_name)", &row).unwrap();
        assert!(matches!(result, ColumnValue::String(s) if s == "JOHN"));

        // Test arithmetic
        row.insert("price".to_string(), ColumnValue::Float64(100.0));
        row.insert("discount".to_string(), ColumnValue::Float64(0.1));
        let result = evaluator.evaluate("price * discount", &row).unwrap();
        // Result may be Int64(10) or Float64(10.0) depending on fractional part
        match result {
            ColumnValue::Float64(f) => assert!((f - 10.0).abs() < 0.001),
            ColumnValue::Int64(i) => assert_eq!(i, 10),
            _ => panic!("expected numeric result"),
        }
    }

    #[test]
    fn test_by_default_identity() {
        let manager = GeneratedColumnsManager::new();

        let identity = IdentityColumnBuilder::new("id")
            .by_default()
            .build("public", "users");

        manager
            .add_identity_column("public", "users", identity)
            .unwrap();

        // BY DEFAULT allows explicit values
        let result = manager.validate_identity_insert(
            "public",
            "users",
            &["id".to_string(), "name".to_string()],
            &[
                ColumnValue::Int64(100),
                ColumnValue::String("test".to_string()),
            ],
        );
        assert!(result.is_ok());
    }
}
